version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/fastapi

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
